#Pandas is one of the important data analysis tool kit ---- Pandas is a Package
--> Using pandas library developer or data analyst fill missing data if they found in the project
--> We can insert,delete the  records
--> we can do data alignment
--> We can do transformation and data aggrigation (Group by)
-->Pandas slicing indexing and subsetting
-->we can work with tables and joins, merging etc
-->Read files (Any Files) using pandas

In [ ]:
#Country GDP or Economic Data Analysis
#import the necessary pandas libraries
import pandas as pd

version = pd.__version__
print(f"Pandas version: {version}") 
import matplotlib.pyplot as plt

Pandas version: 2.3.3

In [ ]:
#Read the excel file and store it in a DataFrame
df = pd.read_excel(r'C:\\Data Science AI Course\\March 31\\data.xlsx')

df

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [ ]:
len(df) #length of the excel file ( rows in the excel file)

195

In [ ]:
df.shape #Shape of the excel file ( rows and columns in the excel file)

(195, 5)

In [ ]:
df.columns #Columns in the excel file

Index(['CountryName', 'CountryCode', 'BirthRate', 'InternetUsers',
       'IncomeGroup'],
      dtype='object')

In [ ]:
len(df.columns ) #Number of columns in the excel file

5

In [ ]:
df.iloc[0:5] #

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [ ]:
df.isnull() #Check for null values in the excel file

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [ ]:
df.isna() #Check for null values in the excel file

     CountryName  CountryCode  BirthRate  InternetUsers  IncomeGroup
0          False        False      False          False        False
1          False        False      False          False        False
2          False        False      False          False        False
3          False        False      False          False        False
4          False        False      False          False        False
..           ...          ...        ...            ...          ...
190        False        False      False          False        False
191        False        False      False          False        False
192        False        False      False          False        False
193        False        False      False          False        False
194        False        False      False          False        False

[195 rows x 5 columns]

In [ ]:
df.isnull().sum() #Check for null values in the excel file and sum them up to get the total number of null values in each column

CountryName      0
CountryCode      0
BirthRate        0
InternetUsers    0
IncomeGroup      0
dtype: int64

In [ ]:
type(df) #Check the type of the DataFrame

pandas.core.frame.DataFrame

In [ ]:
id(df) #Check the memory address of the DataFrame

2039836107824

In [ ]:
df.info() #Check the information about the DataFrame such as the number of non-null values, data types of each column, and memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

In [29]:
df.dtypes #Check the data types of each column in the DataFrame

CountryName       object
CountryCode       object
BirthRate        float64
InternetUsers    float64
IncomeGroup       object
dtype: object

In [31]:
df.head() #Check the first 5 rows of the Excel file

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [32]:
df.tail() #Check the last 5 rows of the Excel file

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [ ]:
df.head(10) #Check the first 10 rows of the Excel file

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9000,Low income
3,Albania,ALB,12.877,57.2000,Upper middle income
2,Angola,AGO,45.985,19.1000,Upper middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
0,Aruba,ABW,10.244,78.9000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income
4,United Arab Emirates,ARE,11.044,88.0000,High income

In [38]:
df.head(10).sort_values(by='CountryName') #Check the first 10 rows of the Excel file and sort them by the 'CountryName' column

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
1,Afghanistan,AFG,35.253,5.9000,Low income
3,Albania,ALB,12.877,57.2000,Upper middle income
2,Angola,AGO,45.985,19.1000,Upper middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
0,Aruba,ABW,10.244,78.9000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income
4,United Arab Emirates,ARE,11.044,88.0000,High income

In [39]:
df[:] #Check all the rows of the Excel file

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [40]:
df[:5] #Check the first 5 rows of the Excel file

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

In [43]:
df[5:10] #Check the rows from index 5 to 9 of the Excel file

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
5,Argentina,ARG,17.716,59.9000,High income
6,Armenia,ARM,13.308,41.9000,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4000,High income
8,Australia,AUS,13.200,83.0000,High income
9,Austria,AUT,9.400,80.6188,High income

In [45]:
df[3:] #Check the rows from index 3 to the end of the Excel file

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income
5,Argentina,ARG,17.716,59.9,High income
6,Armenia,ARM,13.308,41.9,Lower middle income
7,Antigua and Barbuda,ATG,16.447,63.4,High income
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Lower middle income
191,South Africa,ZAF,20.850,46.5,Upper middle income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income
194,Zimbabwe,ZWE,35.715,18.5,Low income

In [46]:
df[0:200:20] #Check the rows from index 0 to 199 with a step of 20 in the Excel file

    CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0         Aruba         ABW     10.244        78.9000          High income
20      Belarus         BLR     12.500        54.1700  Upper middle income
40   Costa Rica         CRI     15.022        45.9600  Upper middle income
60        Gabon         GAB     30.555         9.2000  Upper middle income
80        India         IND     20.291        15.1000  Lower middle income
100       Libya         LBY     21.425        16.5000  Upper middle income
120  Mozambique         MOZ     39.705         5.4000           Low income
140      Poland         POL      9.600        62.8492          High income
160    Suriname         SUR     18.455        37.4000  Upper middle income
180     Uruguay         URY     14.374        57.6900          High income

In [47]:
df[::10] #Check every 10th row of the Excel file starting from index 0

     CountryName CountryCode  BirthRate  InternetUsers          IncomeGroup
0          Aruba         ABW     10.244      78.900000          High income
10    Azerbaijan         AZE     18.300      58.700000  Upper middle income
20       Belarus         BLR     12.500      54.170000  Upper middle income
30        Canada         CAN     10.900      85.800000          High income
40    Costa Rica         CRI     15.022      45.960000  Upper middle income
50       Ecuador         ECU     21.070      40.353684  Upper middle income
60         Gabon         GAB     30.555       9.200000  Upper middle income
70     Greenland         GRL     14.500      65.800000          High income
80         India         IND     20.291      15.100000  Lower middle income
90    Kazakhstan         KAZ     22.730      54.000000  Upper middle income
100        Libya         LBY     21.425      16.500000  Upper middle income
110      Moldova         MDA     12.141      45.000000  Lower middle income
120   Mozambique         MOZ     39.705       5.400000           Low income
130  Netherlands         NLD     10.200      93.956400          High income
140       Poland         POL      9.600      62.849200          High income
150        Sudan         SDN     33.477      22.700000  Lower middle income
160     Suriname         SUR     18.455      37.400000  Upper middle income
170   Tajikistan         TJK     30.792      16.000000  Lower middle income
180      Uruguay         URY     14.374      57.690000          High income
190  Yemen, Rep.         YEM     32.947      20.000000  Lower middle income

In [48]:
df[::-10] #Check every 10th row of the Excel file starting from the end of the file

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
194,Zimbabwe,ZWE,35.715,18.5000,Low income
184,"Venezuela, RB",VEN,19.842,54.9000,High income
174,Trinidad and Tobago,TTO,14.590,63.8000,High income
164,Swaziland,SWZ,30.093,24.7000,Lower middle income
154,Sierra Leone,SLE,36.729,1.7000,Low income
144,French Polynesia,PYF,16.393,56.8000,High income
134,Oman,OMN,20.419,66.4500,High income
124,Malaysia,MYS,16.805,66.9700,Upper middle income
114,"Macedonia, FYR",MKD,11.222,65.2400,Upper middle income
104,Lesotho,LSO,28.738,5.0000,Lower middle income
94,Kiribati,KIR,29.044,11.5000,Lower middle income
84,Iceland,ISL,13.400,96.5468,High income
74,"Hong Kong SAR, China",HKG,7.900,74.2000,High income
64,Guinea,GIN,37.337,1.6000,Low income
54,Estonia,EST,10.300,79.4000,High income
44,Czech Republic,CZE,10.200,74.1104,High income
34,Cote d'Ivoire,CIV,37.320,8.4000,Lower middle income
24,Brazil,BRA,14.931,51.0400,Upper middle income
14,Burkina Faso,BFA,40.551,9.1000,Low income
4,United Arab Emirates,ARE,11.044,88.0000,High income